version: "3.8"
services:
  auto-deployment-agent:
    build:
      target: development
    image: local/deployment-agent:development
    volumes:
      - ./:/devel/services/deployment-agent
    environment:
      - SC_BOOT_MODE=debug-ptvsd
    ports:
      - "3005:3000"
